obstacle_range: 5.0
raytrace_range: 5.5
footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
map_type: costmap
robot_base_frame: base_link

observation_sources: laser_scan_sensor
laser_scan_sensor:
  data_type: LaserScan 
  topic: scan_front
  marking: true
  clearing: true
  min_obstacle_height: -100
  max_obstacle_height: 100