global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false
  origin_x: -10
  origin_y: -10
  width: 30
  height: 30
  resolution: 0.05
  min_obstacle_height: -100
  max_obstacle_height: 100